# Site settings
title: CI and CD with GitHub
description: Surely something useful could be here?
email: patrickbm@github.com
github_username:  patrickbm
baseurl:
url: https://patrickbm-velocity.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

markdown: kramdown
